resources:
  - name: go_gitRepo
    type: GitRepo
    configuration:
      path: avinci/swampup-go-service
      gitProvider: avinci_pipelines

pipelines:
  - name: app
    steps:
      - name: build_go_service
        type: Bash
        configuration:
          integrations:
            - name: art
          inputResources:
            - name: go_gitRepo
        execution:
          onExecute:
            - printenv

      - name: bld_go_service
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: avinci/foo
          dockerImageTag: latest
          inputResources:
            - name: go_gitRepo
