resources:
  - name: go_gitRepo
    type: GitRepo
    configuration:
      path: avinci/swampup-go-service
      gitProvider: avinci_pipelines

pipelines:
  - name: demo
    steps:
      - name: build_go_service
        type: Bash
        configuration:
          integrations:
            - name: art
          inputResources:
            - name: go_gitRepo
        execution:
          onExecute:
            - printenv

      - name: bld_go_svc
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.110.173:8081/docker-local/gosvc
          dockerImageTag: latest
          inputResources:
            - name: go_gitRepo
          integrations:
            - name: art

      - name: push_go_svc
        type: Push
        configuration:
          targetRepo: docker
          integrations:
            - name: art
          inputSteps:
            - name: bld_go_svc
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - art
            - notifySlack
        triggeredBy:
          steps:
            - dockerBuild