resources:
  - name: go_gitRepo
    type: GitRepo
    configuration:
      path: avinci/swampup-go-service
      gitProvider: avinci_pipelines

  - name: svc_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: svc_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: backend_gitRepo
    type: GitRepo
    configuration:
      path: avinci/swampup-java-backend-service
      gitProvider: avinci_pipelines

  - name: app_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: app_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: frontend_gitRepo
    type: GitRepo
    configuration:
      path: avinci/swampup-vue-frontend
      gitProvider: avinci_pipelines

  - name: frontend_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: frontend_build
      buildNumber: 1

  - name: frontend_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: frontend_build
      buildNumber: 1

  - name: releaseBundle
    type: ReleaseBundle
    configuration:
      sourceArtifactory: art
      name: demo
      version: v1.0.0

  - name: signedBundle
    type: ReleaseBundle
    configuration:
      sourceArtifactory: art
      name: demo
      version: v1.0.0

pipelines:
  - name: demo_service
    steps:
      - name: bld_svc
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.110.173:8081/docker-local/gosvc
          dockerImageTag: latest
          inputResources:
            - name: go_gitRepo
          integrations:
            - name: art

      - name: push_svc
        type: PushArtifactoryPackage
        configuration:
          targetRepo: docker-local
          integrations:
            - name: art
          inputSteps:
            - name: bld_svc

      - name: publish_svc_build
        type: PublishBuildInfo
        configuration:
          integrations:
            - name: art
          inputSteps:
            - name: push_svc
          outputResources:
            - name: svc_build_info

      - name: promote_svc_build
        type: PromoteBuild
        configuration:
          integrations:
            - name: art
          inputResources:
            - name: svc_build_info
          inputSteps:
            - name: publish_svc_build
          outputResources:
            - name: svc_promoted_build_info

  - name: demo_app
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: backend_gitRepo
          integrations:
            - name: art
        execution:
          onStart:
            - apt-get update
            - apt install default-jdk
            - pushd /tmp
            - wget http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
            - tar xzvf apache-maven-3.6.1-bin.tar.gz
            - export PATH=$PATH:/tmp/apache-maven-3.6.1/bin
            - export M2_HOME=/tmp/apache-maven-3.6.1/
            - popd
            - javac -version
            - mvn --version

      - name: bld_frontend
        type: NpmBuild
        configuration:
          sourceLocation: .
          repositoryName: npm-dev-virtual
          inputResources:
            - name: frontend_gitRepo
          integrations:
            - name: art

      - name: publish_frontend
        type: NpmPublish
        configuration:
          repositoryName: npm-libs-local
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: art

      - name: build_app
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: 34.66.110.173:8081/docker-local/demo/app
          inputResources:
            - name: backend_gitRepo
          inputSteps:
            - name: bld_backend
            - name: publish_frontend
          integrations:
            - name: art
        execution:
          onStart:
            - pushd $res_backend_gitRepo_resourcePath
            - echo $int_art_url
            - echo $runNumber
            - add_run_variable ${step_name}_buildNumber=${runNumber}
            - add_run_variable ${step_name}_buildName=${pipelineName}
            - docker build -t $dockerImageName:$runNumber --build-arg REGISTRY=${int_art_url} .
            - jfrog rt bce $pipelineName $runNumber
            - jfrog rt docker-push $dockerImageName:$runNumber docker-local --build-name=$pipelineName --build-number=$runNumber
            - save_run_state /tmp/jfrog/. jfrog

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          integrations:
            - name: art
          inputSteps:
            - name: build_app
          outputResources:
            - name: app_build_info

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepo: demo
          integrations:
            - name: art
          inputResources:
            - name: app_build_info
          inputSteps:
            - name: publish_app_build
          outputResources:
            - name: app_promoted_build_info

  - name: demo
    steps:
#      - name: promote_frontend_build
#        type: PromoteBuild
#        configuration:
#          targetRepo: drydock
#          integrations:
#            - name: art
#          inputResources:
#            - name: frontend_build_info
#          inputSteps:
#            - name: publish_frontend_build
#          outputResources:
#            - name: frontend_promoted_build_info

      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo
          releaseBundleVersion: v1.0.0
          dryRun: false
          sign: false
          description: "some random test description"
          integrations:
            - name: art
          inputResources:
            - name: svc_promoted_build_info
              trigger: false
            - name: app_promoted_build_info
              trigger: false
          outputResources:
            - name: releaseBundle
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points

      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: releaseBundle
          integrations:
            - name: art
          outputResources:
            - name: signedBundle